apiVersion: v1
kind: Service
metadata:
  labels:
    app: adventureworks
  name: adventureworks
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    app: adventureworks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adventureworks
  name: adventureworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventureworks
  template:
    metadata:
      labels:
        app: adventureworks
    spec:
      containers:
        - image: phillipsj/adventureworks:20210905
          name: db
          ports:
            - containerPort: 1433
          resources: {}
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.wb.entrypoints: adventureworks-app
    traefik.http.routers.web.rule: Host(`localhost`)
  labels:
    app: adventureworks-app
  name: adventureworks-app
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 80
  selector:
    app: adventureworks-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.wb.entrypoints: adventureworks-app
    traefik.http.routers.web.rule: Host(`localhost`)
  labels:
    app: adventureworks-app
  name: adventureworks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventureworks-app
  strategy: {}
  template:
    metadata:
      annotations:
        traefik.enable: "true"
        traefik.http.routers.wb.entrypoints: adventureworks-app
        traefik.http.routers.web.rule: Host(`localhost`)
      labels:
        app: adventureworks-app
    spec:
      containers:
      - env:
        - name: ConnectionStrings__AdventureWorks
          value: Data Source=db;Initial Catalog=AdventureWorks2019;Integrated Security=False;User
            Id=sa;Password=ThisIsNotASecurePassword123;MultipleActiveResultSets=True
        image: phillipsj/adventureworks-app:v0.1.0
        name: adventureworks-app
        ports:
        - containerPort: 80
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - windows
